version: '3.9'

services:

  web:
    build: .
    container_name: django-torkan-reserve
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./static:/code/static
      -  static_volume:/code/staticfiles
    ports:
      - "8000:8000"

    environment:
      - "DJANGO_DEBUG=False"
    restart: always

  web_server:
    image: nginx:stable-alpine3.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - ./acme-challenge:/var/www/html/.well-known/acme-challenge:ro
      - ~/ssl_certs/zarnobat.ir:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    restart: always
volumes:
  postgres_data:
  static_volume: