version: '3.9'

services:

  web:
    build: .
    container_name: web-dev
    command: python /code/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

    environment:
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:17-alpine
    container_name: db-dev
    ports:
      - "5432:5432"
    env_file:
      - .env

    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"

    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    container_name: redis-dev
    ports:
      - "6379:6379"