version: '3.9'

services:

  web:
    build: .
    container_name: django-torkan-reserve
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 4 --worker-class gthread --timeout 120
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./static:/code/static
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    # ports:
    #   - "8000:8000"
    environment:
      - "DJANGO_DEBUG=False"
    restart: always

  daphne:
    build: .
    container_name: django-daphne
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./static:/code/static
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    ports:
      - "8001:8001"
    environment:
      - "DJANGO_DEBUG=False"
    restart: always

  web_server:
    image: nginx:stable-alpine3.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/static:ro
      - ./media:/media:ro
      - ./acme-challenge:/var/www/html/.well-known/acme-challenge:ro
      - ./ssl_certs:/etc/nginx/ssl:ro
    depends_on:
      - web
      - daphne
    restart: always

  db:
    image: postgres:17-alpine
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    restart: always

  redis:
    image: redis:alpine3.22
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: