version: '3.9'

services:

  web:
    build: .
    container_name: web
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./static:/code/static
      -  static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"

    environment:
      - "DJANGO_DEBUG=True"
    restart: always

  web_server:
    image: nginx:stable-alpine3.21
    container_name: web-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro 
      # - ./acme-challenge:/var/www/html/.well-known/acme-challenge:ro
      - ./cert:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "65432:5432"
    env_file:
      - .env

    volumes:
      - database:/var/lib/postgresql/data

    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    restart: always

  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  database:
  static_volume:
  media_volume: