# Generated by Django 5.1.7 on 2025-08-31 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('name', models.CharField(max_length=100, verbose_name='First and last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active ?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff ?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser ?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': ' پروفایل\u200c مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مساعده'), ('other', 'سایر')], help_text='نوع درخواست یا مشکل را انتخاب کنید.', max_length=20, verbose_name='نوع تیکت')),
                ('leave_start', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع مرخصی')),
                ('leave_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان مرخصی')),
                ('leave_type', models.CharField(blank=True, choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], max_length=20, null=True, verbose_name='نوع مرخصی')),
                ('facility_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ تسهیلات')),
                ('facility_duration_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت بازپرداخت (ماه)')),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ مساعده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('employee', models.ForeignKey(help_text='کارمند ایجادکننده این تیکت را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'تیکت کارمند',
                'verbose_name_plural': 'تیکت های کارمندان',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTicketProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تیکت کارمند',
                'verbose_name_plural': 'تیکت\u200c کارمند ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.employeeticket',),
        ),
        migrations.CreateModel(
            name='EmployeeTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='متن پاسخ.', verbose_name='متن پاسخ')),
                ('created_at', models.DateField(auto_now_add=True, help_text='تاریخ و زمان ایجاد پاسخ.', verbose_name='تاریخ ایجاد')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='ضمیمه')),
                ('status_ticket', models.CharField(choices=[('agreed', 'موافقت شده'), ('in_progress', 'در حال بررسی'), ('rejected', 'رد شده')], default='in_progress', help_text='وضعیت فعلی تیکت.', max_length=20, verbose_name='وضعیت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20)),
                ('author', models.ForeignKey(editable=False, help_text='نویسنده پاسخ (کارمند یا ادمین).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پاسخ')),
                ('ticket', models.ForeignKey(help_text='تیکتی که این پاسخ مربوط به آن است.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.employeeticket', verbose_name='تیکت مرتبط')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت کارمند',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت کارمندان',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='فاکتور')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='تاریخ پیوستن')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'پروفایل کارمند',
                'verbose_name_plural': 'پروفایل کارمند ها',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'مشتری'), ('staff', 'کارمند')], max_length=10, verbose_name='نوع کاربر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن پیشنهاد/انتقاد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False, editable=False, verbose_name='بررسی شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'انتقاد/پیشنهاد',
                'verbose_name_plural': 'انتقادات و پیشنهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'تیکت مشتری',
                'verbose_name_plural': 'تیکت\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تیکت مشتری',
                'verbose_name_plural': 'تیکت مشتری ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.supportticket',),
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.supportticket')),
            ],
            options={
                'verbose_name': 'پاسخ پشتیبانی',
                'verbose_name_plural': 'پاسخ های پشتیبانی',
            },
        ),
        migrations.CreateModel(
            name='WorkHourReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1400, '1400'), (1401, '1401'), (1402, '1402'), (1403, '1403'), (1404, '1404'), (1405, '1405'), (1406, '1406'), (1407, '1407'), (1408, '1408'), (1409, '1409'), (1410, '1410'), (1411, '1411'), (1412, '1412'), (1413, '1413'), (1414, '1414'), (1415, '1415'), (1416, '1416'), (1417, '1417'), (1418, '1418'), (1419, '1419'), (1420, '1420'), (1421, '1421'), (1422, '1422'), (1423, '1423'), (1424, '1424'), (1425, '1425'), (1426, '1426'), (1427, '1427'), (1428, '1428'), (1429, '1429'), (1430, '1430'), (1431, '1431'), (1432, '1432'), (1433, '1433'), (1434, '1434'), (1435, '1435'), (1436, '1436'), (1437, '1437'), (1438, '1438'), (1439, '1439'), (1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449')], verbose_name='سال')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('duty_hours', models.IntegerField(verbose_name='ساعت موظفی')),
                ('overtime', models.IntegerField(verbose_name='اضافه کاری')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'گزارش ساعت کاری',
                'verbose_name_plural': 'گزارش\u200cهای ساعت کاری',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1400, '1400'), (1401, '1401'), (1402, '1402'), (1403, '1403'), (1404, '1404'), (1405, '1405'), (1406, '1406'), (1407, '1407'), (1408, '1408'), (1409, '1409'), (1410, '1410'), (1411, '1411'), (1412, '1412'), (1413, '1413'), (1414, '1414'), (1415, '1415'), (1416, '1416'), (1417, '1417'), (1418, '1418'), (1419, '1419'), (1420, '1420'), (1421, '1421'), (1422, '1422'), (1423, '1423'), (1424, '1424'), (1425, '1425'), (1426, '1426'), (1427, '1427'), (1428, '1428'), (1429, '1429'), (1430, '1430'), (1431, '1431'), (1432, '1432'), (1433, '1433'), (1434, '1434'), (1435, '1435'), (1436, '1436'), (1437, '1437'), (1438, '1438'), (1439, '1439'), (1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449')], verbose_name='سال')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payslip_image', models.FileField(blank=True, null=True, upload_to='payslip/', verbose_name='فیش حقوقی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile', verbose_name='کارمند')),
                ('work_hour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.workhourreport', verbose_name='گزارش کارکرد ماهانه')),
            ],
            options={
                'verbose_name': 'فیش حقوقی',
                'verbose_name_plural': 'فیش\u200cهای حقوقی',
            },
        ),
    ]
