# Generated by Django 5.1.7 on 2025-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ مساعده'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ تسهیلات'),
        ),
    ]
