# Generated by Django 5.1.7 on 2025-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
