# Generated by Django 5.1.7 on 2025-08-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'پروفایل مشتری', 'verbose_name_plural': 'پروفایل مشتری\u200cها'},
        ),
    ]
