# Generated by Django 5.1.7 on 2025-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_suggestion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'ارسال شده'), ('pending', 'در انتظار'), ('faild', 'نا موفق')], max_length=50)),
            ],
        ),
    ]
