# Generated by Django 5.1.7 on 2025-09-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ارسال پیامک',
                'verbose_name_plural': ' هارسال پیامک ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.smslog',),
        ),
    ]
