# Generated by Django 5.1.7 on 2025-09-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_smsproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsLog',
        ),
        migrations.DeleteModel(
            name='SMSProxy',
        ),
    ]
