# Generated by Django 5.1.7 on 2025-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_smslog_delete_smsproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.PositiveIntegerField(help_text='09123456789', max_length=15, verbose_name='شماره همراه گیرنده')),
                ('messges', models.CharField(default='https://maps.app.goo.gl/HKXdXNXsLz7B1dNS7', max_length=255, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
