# Generated by Django 5.1.7 on 2025-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='receiver',
            field=models.PositiveIntegerField(help_text='09123456789', verbose_name='شماره همراه گیرنده'),
        ),
    ]
