# Generated by Django 5.1.7 on 2025-09-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_sms_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
