# Generated by Django 5.1.7 on 2025-08-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customerprofile_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='history_reserve',
        ),
    ]
