# Generated by Django 5.1.7 on 2025-08-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ticketreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='responder',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده'),
        ),
    ]
