# Generated by Django 5.1.7 on 2025-08-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'تیکت مشتری', 'verbose_name_plural': 'تیکت\u200cهای مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'verbose_name': 'پاسخ پشتیبانی', 'verbose_name_plural': 'پاسخ های پشتیبانی'},
        ),
    ]
