# Generated by Django 5.1.7 on 2025-08-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20),
        ),
    ]
