# Generated by Django 5.1.7 on 2025-08-07 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_supportticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='invoice',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='فاکتور')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
