# Generated by Django 5.1.7 on 2025-08-09 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('date_joined', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHourReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1400, '1400'), (1401, '1401'), (1402, '1402'), (1403, '1403'), (1404, '1404'), (1405, '1405'), (1406, '1406'), (1407, '1407'), (1408, '1408'), (1409, '1409'), (1410, '1410'), (1411, '1411'), (1412, '1412'), (1413, '1413'), (1414, '1414'), (1415, '1415'), (1416, '1416'), (1417, '1417'), (1418, '1418'), (1419, '1419'), (1420, '1420'), (1421, '1421'), (1422, '1422'), (1423, '1423'), (1424, '1424'), (1425, '1425'), (1426, '1426'), (1427, '1427'), (1428, '1428'), (1429, '1429'), (1430, '1430'), (1431, '1431'), (1432, '1432'), (1433, '1433'), (1434, '1434'), (1435, '1435'), (1436, '1436'), (1437, '1437'), (1438, '1438'), (1439, '1439'), (1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449')], verbose_name='سال')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('duty_hours', models.IntegerField(verbose_name='ساعت موظفی')),
                ('overtime', models.IntegerField(verbose_name='اضافه کاری')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1400, '1400'), (1401, '1401'), (1402, '1402'), (1403, '1403'), (1404, '1404'), (1405, '1405'), (1406, '1406'), (1407, '1407'), (1408, '1408'), (1409, '1409'), (1410, '1410'), (1411, '1411'), (1412, '1412'), (1413, '1413'), (1414, '1414'), (1415, '1415'), (1416, '1416'), (1417, '1417'), (1418, '1418'), (1419, '1419'), (1420, '1420'), (1421, '1421'), (1422, '1422'), (1423, '1423'), (1424, '1424'), (1425, '1425'), (1426, '1426'), (1427, '1427'), (1428, '1428'), (1429, '1429'), (1430, '1430'), (1431, '1431'), (1432, '1432'), (1433, '1433'), (1434, '1434'), (1435, '1435'), (1436, '1436'), (1437, '1437'), (1438, '1438'), (1439, '1439'), (1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449')])),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payslip_image', models.FileField(blank=True, null=True, upload_to='payslip/', verbose_name='فیش حقوقی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('work_hour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.workhourreport', verbose_name='گزارش کارکرد ماهانه')),
            ],
        ),
    ]
