# Generated by Django 5.1.7 on 2025-08-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staffprofile_workhourreport_payslip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'فیش حقوقی', 'verbose_name_plural': 'فیش\u200cهای حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'پروفایل کارمند', 'verbose_name_plural': 'پروفایل\u200cهای کارمندان'},
        ),
        migrations.AlterModelOptions(
            name='workhourreport',
            options={'verbose_name': 'گزارش ساعت کاری', 'verbose_name_plural': 'گزارش\u200cهای ساعت کاری'},
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(choices=[(1400, '1400'), (1401, '1401'), (1402, '1402'), (1403, '1403'), (1404, '1404'), (1405, '1405'), (1406, '1406'), (1407, '1407'), (1408, '1408'), (1409, '1409'), (1410, '1410'), (1411, '1411'), (1412, '1412'), (1413, '1413'), (1414, '1414'), (1415, '1415'), (1416, '1416'), (1417, '1417'), (1418, '1418'), (1419, '1419'), (1420, '1420'), (1421, '1421'), (1422, '1422'), (1423, '1423'), (1424, '1424'), (1425, '1425'), (1426, '1426'), (1427, '1427'), (1428, '1428'), (1429, '1429'), (1430, '1430'), (1431, '1431'), (1432, '1432'), (1433, '1433'), (1434, '1434'), (1435, '1435'), (1436, '1436'), (1437, '1437'), (1438, '1438'), (1439, '1439'), (1440, '1440'), (1441, '1441'), (1442, '1442'), (1443, '1443'), (1444, '1444'), (1445, '1445'), (1446, '1446'), (1447, '1447'), (1448, '1448'), (1449, '1449')], verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_joined',
            field=models.DateField(verbose_name='تاریخ پیوستن'),
        ),
        migrations.AlterField(
            model_name='workhourreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile', verbose_name='کارمند'),
        ),
    ]
