# Generated by Django 5.1.7 on 2025-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_payslip_options_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
