# Generated by Django 5.1.7 on 2025-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_staffprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
