# Generated by Django 5.1.7 on 2025-08-09 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_staffprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
    ]
