# Generated by Django 5.1.7 on 2025-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_staffprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ پیوستن'),
        ),
    ]
