# Generated by Django 5.1.7 on 2025-08-10 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_staffprofile_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مسائده'), ('other', 'سایر')], max_length=20)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField()),
                ('leave_type', models.CharField(choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], max_length=20)),
                ('facility_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facility_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_description', models.TextField()),
                ('other_description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته شده')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
