# Generated by Django 5.1.7 on 2025-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_employeeticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticket',
            name='facility_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='leave_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
