# Generated by Django 5.1.7 on 2025-08-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_employeeticket_facility_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeticket',
            name='advance_description',
        ),
        migrations.RemoveField(
            model_name='employeeticket',
            name='facility_description',
        ),
        migrations.RemoveField(
            model_name='employeeticket',
            name='leave_description',
        ),
        migrations.RemoveField(
            model_name='employeeticket',
            name='other_description',
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی در مورد درخواست خود را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ مساعده درخواستی را وارد کنید.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد (سیستمی).'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='employee',
            field=models.ForeignKey(help_text='کارمند ایجادکننده این تیکت را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ تسهیلات مورد نظر را وارد کنید.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='مدت بازپرداخت تسهیلات به ماه.', null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_end',
            field=models.DateField(blank=True, help_text='تاریخ پایان مرخصی را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_start',
            field=models.DateField(blank=True, help_text='تاریخ شروع مرخصی را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], help_text='نوع مرخصی را انتخاب کنید.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته شده')], default='open', help_text='وضعیت فعلی تیکت.', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='ticket_type',
            field=models.CharField(choices=[('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مساعده'), ('other', 'سایر')], help_text='نوع درخواست یا مشکل را انتخاب کنید.', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ آخرین بروزرسانی (سیستمی).'),
        ),
    ]
