# Generated by Django 5.1.7 on 2025-08-10 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_employeeticket_advance_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='متن پاسخ.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد پاسخ.')),
                ('is_read', models.BooleanField(default=False, help_text='آیا این پاسخ توسط گیرنده خوانده شده است؟')),
                ('author', models.ForeignKey(help_text='نویسنده پاسخ (کارمند یا ادمین).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='تیکتی که این پاسخ مربوط به آن است.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.employeeticket')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت کارمند',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت کارمندان',
                'ordering': ['created_at'],
            },
        ),
    ]
