# Generated by Django 5.1.7 on 2025-08-10 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_employeeticketreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeticketreply',
            name='author',
            field=models.ForeignKey(editable=False, help_text='نویسنده پاسخ (کارمند یا ادمین).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
