# Generated by Django 5.1.7 on 2025-08-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_employeeticketreply_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeticket',
            options={'ordering': ['created_at'], 'verbose_name': ' تیکت کارمند', 'verbose_name_plural': ' تیکت های کارمندان'},
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ مساعده درخواستی را وارد کنید.', max_digits=12, null=True, verbose_name='مبلغ مساعده'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد (سیستمی).', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی در مورد درخواست خود را وارد کنید.', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='employee',
            field=models.ForeignKey(help_text='کارمند ایجادکننده این تیکت را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ تسهیلات مورد نظر را وارد کنید.', max_digits=12, null=True, verbose_name='مبلغ تسهیلات'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='مدت بازپرداخت تسهیلات به ماه.', null=True, verbose_name='مدت بازپرداخت (ماه)'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_end',
            field=models.DateField(blank=True, help_text='تاریخ پایان مرخصی را وارد کنید.', null=True, verbose_name='تاریخ پایان مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_start',
            field=models.DateField(blank=True, help_text='تاریخ شروع مرخصی را وارد کنید.', null=True, verbose_name='تاریخ شروع مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], help_text='نوع مرخصی را انتخاب کنید.', max_length=20, null=True, verbose_name='نوع مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته شده')], default='open', help_text='وضعیت فعلی تیکت.', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='ticket_type',
            field=models.CharField(choices=[('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مساعده'), ('other', 'سایر')], help_text='نوع درخواست یا مشکل را انتخاب کنید.', max_length=20, verbose_name='نوع تیکت'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ آخرین بروزرسانی (سیستمی).', verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='author',
            field=models.ForeignKey(editable=False, help_text='نویسنده پاسخ (کارمند یا ادمین).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پاسخ'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد پاسخ.', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='is_read',
            field=models.BooleanField(default=False, help_text='آیا این پاسخ توسط گیرنده خوانده شده است؟', verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='message',
            field=models.TextField(help_text='متن پاسخ.', verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='ticket',
            field=models.ForeignKey(help_text='تیکتی که این پاسخ مربوط به آن است.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.employeeticket', verbose_name='تیکت مرتبط'),
        ),
    ]
