# Generated by Django 5.1.7 on 2025-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_employeeticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeticket',
            name='ticket_type',
            field=models.CharField(choices=[('suggestions', 'انتقادات و پیشنهادات'), ('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مساعده'), ('other', 'سایر')], help_text='نوع درخواست یا مشکل را انتخاب کنید.', max_length=20, verbose_name='نوع تیکت'),
        ),
    ]
