# Generated by Django 5.1.7 on 2025-08-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_employeeticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeticket',
            name='status',
        ),
        migrations.AddField(
            model_name='employeeticketreply',
            name='status',
            field=models.CharField(choices=[('agreed', 'موافقت شده'), ('in_progress', 'در حال بررسی'), ('rejected', 'رد شده')], default='in_progress', help_text='وضعیت فعلی تیکت.', max_length=20, verbose_name='وضعیت'),
        ),
    ]
