# Generated by Django 5.1.7 on 2025-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_employeeticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeticketreply',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
