# Generated by Django 5.1.7 on 2025-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_employeeticketreply_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticketreply',
            name='status_ticket',
            field=models.CharField(choices=[('agreed', 'موافقت شده'), ('in_progress', 'در حال بررسی'), ('rejected', 'رد شده')], default='in_progress', help_text='وضعیت فعلی تیکت.', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='employeeticketreply',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20),
        ),
    ]
