# Generated by Django 5.1.7 on 2025-08-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_employeeticketreply_status_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTicketProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تیکت کارمند',
                'verbose_name_plural': 'تیکت\u200cهای کارمندان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.employeeticket',),
        ),
    ]
