# Generated by Django 5.1.7 on 2025-08-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_employeeticketproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketProxy',
            fields=[
                ('supportticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.supportticket')),
            ],
            bases=('accounts.supportticket',),
        ),
    ]
