# Generated by Django 5.1.7 on 2025-08-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_supportticketproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicketProxy',
        ),
        migrations.CreateModel(
            name='SupportTicketProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تیکت مشتری',
                'verbose_name_plural': 'تیکت\u200cهای مشتری',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.supportticket',),
        ),
    ]
