# Generated by Django 5.1.7 on 2025-08-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_delete_supportticketproxy_supportticketproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticketproxy',
            options={'verbose_name': 'تیکت مشتری', 'verbose_name_plural': 'تیکت\u200cهای مشتری ها'},
        ),
    ]
