# Generated by Django 5.1.7 on 2025-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_supportticketproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeticket',
            options={'ordering': ['created_at'], 'verbose_name': 'تیکت کارمند', 'verbose_name_plural': 'تیکت های کارمندان'},
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ مساعده'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ تسهیلات'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='facility_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت بازپرداخت (ماه)'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_end',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'استعلاجی'), ('annual', 'استحقاقی'), ('unpaid', 'بدون حقوق')], max_length=20, null=True, verbose_name='نوع مرخصی'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='ticket_type',
            field=models.CharField(choices=[('leave', 'مرخصی'), ('facility', 'تسهیلات'), ('advance', 'مساعده'), ('other', 'سایر')], help_text='نوع درخواست یا مشکل را انتخاب کنید.', max_length=20, verbose_name='نوع تیکت'),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
