# Generated by Django 5.1.7 on 2025-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='user_type',
            field=models.CharField(choices=[('customer', 'مشتری'), ('staff', 'کارمند')], max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
