# Generated by Django 5.1.7 on 2025-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_suggestion_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='is_reviewed',
            field=models.BooleanField(default=False, editable=False, verbose_name='بررسی شده'),
        ),
    ]
