# Generated by Django 5.1.7 on 2025-08-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_suggestion_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'انتقاد/پیشنهاد', 'verbose_name_plural': 'انتقادات و پیشنهادات'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
