# Generated by Django 5.1.7 on 2025-08-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_invoice_options_alter_suggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'پروفایل مشتری', 'verbose_name_plural': ' پروفایل\u200c مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'پروفایل کارمند', 'verbose_name_plural': 'پروفایل کارمند ها'},
        ),
    ]
