# Generated by Django 5.1.7 on 2025-08-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeticketproxy',
            options={'verbose_name': 'تیکت کارمند', 'verbose_name_plural': 'تیکت\u200c کارمند ها'},
        ),
        migrations.AlterModelOptions(
            name='supportticketproxy',
            options={'verbose_name': 'تیکت مشتری', 'verbose_name_plural': 'تیکت مشتری ها'},
        ),
    ]
