# Generated by Django 5.1.7 on 2025-08-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_customerprofile_id_alter_customerprofile_user'),
        ('accounts', '0048_alter_employeeticketproxy_options_and_more'),
    ]

    operations = [
    ]
