# Generated by Django 5.1.7 on 2025-09-04 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ (لینک)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ (لینک)')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ (لینک)')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/', verbose_name='تصویر اصلی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'انتشار')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
