# Generated by Django 5.1.7 on 2025-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='تصویر')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='انتشار؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['-created_at'],
            },
        ),
    ]
