# Generated by Django 5.1.7 on 2025-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(default=0, verbose_name='انتشار؟'),
        ),
    ]
