# Generated by Django 5.1.7 on 2025-08-11 20:46

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=50, verbose_name='Operation name')),
            ],
            options={
                'verbose_name': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='OperationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_capacity', models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=10, null=True, verbose_name='Unit of calculation')),
                ('capacity', models.IntegerField(default=0, verbose_name='Number of furnaces')),
                ('capacity_materials', models.IntegerField(default=1, verbose_name='Material volume')),
                ('zamini', models.BooleanField(default=False, verbose_name='Is there ground melting?')),
                ('Product', models.CharField(blank=True, max_length=20, null=True, verbose_name='Product name')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='Operation type')),
            ],
            options={
                'verbose_name': 'Approximate time',
            },
        ),
        migrations.CreateModel(
            name='RequestReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('suggested_reservation_date', models.DateField(default=home.models.default_reservation_date, verbose_name='reservation date')),
                ('suggested_reservation_time', models.TimeField(blank=True, default='08:00', null=True, verbose_name='suggested reservation time')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reservation requests',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_reserved_date', models.DateField(blank=True, default=home.models.default_reservation_date, null=True, verbose_name='fixed date')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Material volume')),
                ('unit', models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=15, null=True, verbose_name='Unit of calculation')),
                ('start_session', models.TimeField(blank=True, default='08:00', null=True, verbose_name='From the clock')),
                ('end_session', models.TimeField(blank=True, default='12:00', null=True, verbose_name='Up to the hour')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='Operation type')),
                ('request_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.requestreservation', verbose_name='Request reservation')),
            ],
            options={
                'verbose_name': 'Appointment booking',
            },
        ),
    ]
