# Generated by Django 5.1.7 on 2025-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_time_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_session',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='تا ساعت '),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_session',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='از ساعت '),
        ),
    ]
