# Generated by Django 5.1.7 on 2025-05-05 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_time_user_time_date_time_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='date_time_reserved',
        ),
        migrations.RemoveField(
            model_name='time',
            name='shamsi_date',
        ),
        migrations.AddField(
            model_name='requestreservation',
            name='suggested_reservation_time',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='reservation time'),
        ),
        migrations.AddField(
            model_name='time',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='fix_reserved_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='reservation date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_session',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='operation end time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_session',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='operation start time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='unit',
            field=models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=15, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='time',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='volume'),
        ),
    ]
