# Generated by Django 5.1.7 on 2025-05-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_requestreservation_suggested_reservation_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operation',
            table='عملیات ها',
        ),
        migrations.AlterModelTable(
            name='operationsetting',
            table='محاسبه تقریبی زمان',
        ),
        migrations.AlterModelTable(
            name='requestreservation',
            table='درخواست های نوبت',
        ),
        migrations.AlterModelTable(
            name='time',
            table='رزرو نوبت',
        ),
    ]
