# Generated by Django 5.1.7 on 2025-05-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_operation_table_alter_operationsetting_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'عملیات ها'},
        ),
        migrations.AlterModelOptions(
            name='operationsetting',
            options={'verbose_name': 'محاسبه تقریبی زمان'},
        ),
        migrations.AlterModelOptions(
            name='requestreservation',
            options={'verbose_name': 'درخواست های نوبت'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'رزرو نوبت'},
        ),
        migrations.AlterModelTable(
            name='operation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='operationsetting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='requestreservation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='time',
            table=None,
        ),
    ]
