# Generated by Django 5.1.7 on 2025-05-14 06:10

import django.db.models.deletion
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operations'},
        ),
        migrations.AlterModelOptions(
            name='operationsetting',
            options={'verbose_name': 'Approximate time'},
        ),
        migrations.AlterModelOptions(
            name='requestreservation',
            options={'verbose_name': 'Reservation requests'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Appointment booking'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(max_length=50, verbose_name='Operation name'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='Product',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Number of furnaces'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='capacity_materials',
            field=models.IntegerField(default=1, verbose_name='Material volume'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='Operation type'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='unit_capacity',
            field=models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=10, null=True, verbose_name='Unit of calculation'),
        ),
        migrations.AlterField(
            model_name='operationsetting',
            name='zamini',
            field=models.BooleanField(default=False, verbose_name='Is there ground melting?'),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_session',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Up to the hour'),
        ),
        migrations.AlterField(
            model_name='time',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='Operation type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='shamsi_date',
            field=models.DateField(blank=True, default=jdatetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_session',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='From the clock'),
        ),
        migrations.AlterField(
            model_name='time',
            name='unit',
            field=models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=15, null=True, verbose_name='Unit of calculation'),
        ),
        migrations.AlterField(
            model_name='time',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Material volume'),
        ),
    ]
