# Generated by Django 5.1.7 on 2025-05-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_time_date_time_reserved_and_more'),
        ('home', '0008_alter_operation_options_and_more'),
    ]

    operations = [
    ]
