# Generated by Django 5.1.7 on 2025-05-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20250510_1235'),
        ('home', '0010_alter_requestreservation_datetime_created_and_more'),
    ]

    operations = [
    ]
