# Generated by Django 5.1.7 on 2025-05-15 08:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20250515_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_session',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Up to the hour'),
        ),
        migrations.AlterField(
            model_name='time',
            name='fix_reserved_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='Operation type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_session',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='From the clock'),
        ),
        migrations.AlterField(
            model_name='time',
            name='unit',
            field=models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=15, null=True, verbose_name='Unit of calculation'),
        ),
        migrations.AlterField(
            model_name='time',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Material volume'),
        ),
    ]
