# Generated by Django 5.1.7 on 2025-06-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_time_end_session_alter_time_fix_reserved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_time',
            field=models.TimeField(blank=True, default='08:00', null=True, verbose_name='suggested reservation time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='request_reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.requestreservation', verbose_name='Request reservation'),
        ),
    ]
