# Generated by Django 5.1.7 on 2025-06-16 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_time_date_time_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreservation',
            name='explenation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_date',
            field=models.DateField(default=datetime.date(2025, 6, 18), verbose_name='reservation date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='fix_reserved_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='fixed date'),
        ),
    ]
