# Generated by Django 5.1.7 on 2025-06-16 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_requestreservation_explenation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_date',
            field=models.DateField(default=datetime.date(2025, 6, 17), verbose_name='reservation date'),
        ),
    ]
