# Generated by Django 5.1.7 on 2025-06-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_requestreservation_suggested_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestreservation',
            old_name='explenation',
            new_name='explanation',
        ),
    ]
