# Generated by Django 5.1.7 on 2025-06-28 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_explenation_requestreservation_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_date',
            field=models.DateField(default=datetime.date(2025, 6, 28), verbose_name='reservation date'),
        ),
    ]
