# Generated by Django 5.1.7 on 2025-06-28 01:32

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_requestreservation_suggested_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreservation',
            name='suggested_reservation_date',
            field=models.DateField(default=home.models.default_reservation_date, verbose_name='reservation date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='fix_reserved_date',
            field=models.DateField(blank=True, default=home.models.default_reservation_date, null=True, verbose_name='fixed date'),
        ),
    ]
