version: '3.9'
name: torkan-reserve-prod
services:

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: prod-web
    command: sh -c "python manage.py collectstatic --noinput && daphne config.asgi:application --bind 0.0.0.0 --port 8000"
    depends_on:
      - db
      - redis
    env_file:
      - ../env/.env.prod
    volumes:
      - ../static:/code/static
      - ../staticfiles:/code/staticfiles
      - ../media:/code/media
    restart: always
  web_server:
    image: nginx:stable-alpine3.21
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../staticfiles:/static:ro
      - ../media:/media:ro
      - ../acme-challenge:/var/www/html/.well-known/acme-challenge:ro
      - ../cert:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
  db:
    image: postgres:17-alpine
    container_name: db-prod
    # ports:
    #   - "5432:5432"
    env_file:
      - ../env/.env.prod
    volumes:
      - ../postgres_database:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    restart: always
  redis:
    image: redis:alpine3.22
    container_name: redis-prod
    ports:
      - "6379:6379"
    restart: always