# Generated by Django 5.1.7 on 2025-08-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
    ]
