# Generated by Django 5.1.7 on 2025-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(help_text='09123456789', max_length=20, verbose_name='شماره همراه گیرنده')),
                ('message', models.CharField(default='https://maps.app.goo.gl/HKXdXNXsLz7B1dNS7', max_length=255, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
