# Generated by Django 5.1.7 on 2025-09-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='نام گیرنده'),
            preserve_default=False,
        ),
    ]
