# Generated by Django 5.1.7 on 2025-09-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_sms_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['-created_at'], 'verbose_name': 'ارسال پیامک', 'verbose_name_plural': 'ارسال پیامک ها'},
        ),
    ]
