# Generated by Django 5.1.7 on 2025-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
