# Generated by Django 5.1.7 on 2025-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
