# Generated by Django 5.1.7 on 2025-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_sms_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اعلان'),
        ),
    ]
