# Generated by Django 5.1.7 on 2025-09-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ticket_type',
        ),
    ]
