name: Django project deploy

on:
  push:
    branches: [ "deployment" ]
  pull_request:
    branches: [ "deployment" ]

jobs:

  Deploy:
    name: deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Connect to vps by ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: ls
      
